CREATE TABLE IF NOT EXISTS APP_USER (
  id SERIAL PRIMARY KEY,
  email VARCHAR(100) NOT NULL UNIQUE,
  password CHAR(64) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS APP_GROUP (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  description TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CATEGORY (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  description TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS TAG (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  description TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS TASK (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  display_order INTEGER NOT NULL DEFAULT 0,
  priority INTEGER NOT NULL DEFAULT 0,
  completed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (priority >= 0 AND priority <= 5),
  CHECK (display_order >= 0)
);

CREATE TABLE IF NOT EXISTS TASK_EX (
  task_id INTEGER PRIMARY KEY REFERENCES TASK(id) ON DELETE CASCADE,
  due_date TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS USER_GROUP (
  user_id INTEGER NOT NULL REFERENCES APP_USER(id) ON DELETE CASCADE,
  group_id INTEGER NOT NULL REFERENCES APP_GROUP(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, group_id)
);

CREATE TABLE IF NOT EXISTS TASK_USER (
  task_id INTEGER NOT NULL REFERENCES TASK(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES APP_USER(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (task_id, user_id)
);

CREATE TABLE IF NOT EXISTS TASK_CATEGORY (
  task_id INTEGER NOT NULL REFERENCES TASK(id) ON DELETE CASCADE,
  category_id INTEGER NOT NULL REFERENCES CATEGORY(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (task_id, category_id)
);

CREATE TABLE IF NOT EXISTS TASK_TAG (
  task_id INTEGER NOT NULL REFERENCES TASK(id) ON DELETE CASCADE,
  tag_id INTEGER NOT NULL REFERENCES TAG(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (task_id, tag_id)
);

CREATE INDEX IF NOT EXISTS idx_task_ex_due_date ON TASK_EX(due_date);
CREATE INDEX IF NOT EXISTS idx_user_group_user_id ON USER_GROUP(user_id);
CREATE INDEX IF NOT EXISTS idx_user_group_group_id ON USER_GROUP(group_id);
CREATE INDEX IF NOT EXISTS idx_task_user_task_id ON TASK_USER(task_id);
CREATE INDEX IF NOT EXISTS idx_task_user_user_id ON TASK_USER(user_id);
CREATE INDEX IF NOT EXISTS idx_task_category_task_id ON TASK_CATEGORY(task_id);
CREATE INDEX IF NOT EXISTS idx_task_category_category_id ON TASK_CATEGORY(category_id);
CREATE INDEX IF NOT EXISTS idx_task_tag_task_id ON TASK_TAG(task_id);
CREATE INDEX IF NOT EXISTS idx_task_tag_tag_id ON TASK_TAG(tag_id);
